enabled moving of grapg channels
silicon-heaven/libshv pull request #139
Opened 2021-07-07 11:15 UTC by MartinKT

2021-07-08 09:44 UTC, fvacek requested changes

2021-07-08 10:55 UTC, MartinKT commented on libshvvisu/src/timeline/graphwidget.h
> +	QWidget *m_thickYellowLine;
Opraveno.

2021-07-08 11:45 UTC, MartinKT commented on libshvvisu/src/timeline/graphwidget.h
> +	bool scrollOnMouseMove(const QPoint &mouse_pos);
Presne tak.

2021-07-13 14:59 UTC, fvacek commented on libshvvisu/src/timeline/graphwidget.h
> +	bool scrollOnMouseMove(const QPoint &mouse_pos);
pak by se mela jmenovat `scrollByMouseOuterOverlap`

2021-07-13 14:59 UTC, fvacek commented on libshvvisu/src/timeline/graphwidget.h
> +	void scrollOnMouseMove();
???

2021-07-13 15:00 UTC, fvacek commented
co ty ostatni commenty?

2021-07-13 15:01 UTC, fvacek commented on libshvvisu/src/timeline/graphwidget.cpp
> +	moveYellowThickLineAccordingToPos(pos);
`moveDropMarker...`

2021-07-24 08:42 UTC, fvacek requested changes

2021-07-24 08:42 UTC, fvacek commented on libshvvisu/src/timeline/graphwidget.cpp
> +			QRect header_rect;
indentation

2021-07-24 08:42 UTC, fvacek commented on libshvvisu/src/timeline/graphwidget.cpp
> +			delete m_channelHeaderMoveContext->mouseMoveScrollTimer;
should be in m_channelHeaderMoveContext destructor

2021-07-24 08:42 UTC, fvacek commented on libshvvisu/src/timeline/graphwidget.cpp
> +			delete m_channelHeaderMoveContext->channelDropMarker;
should be in m_channelHeaderMoveContext destructor

2021-07-24 08:42 UTC, fvacek commented on libshvvisu/src/timeline/graphwidget.cpp
> +			delete m_channelHeaderMoveContext;
I think that this is possible memory leak to have delete only in this if branch

2021-07-26 08:16 UTC, merged