replace channel filter with view settings
silicon-heaven/libshv pull request #149
Opened 2021-09-13 12:48 UTC by MartinKT

2021-09-13 15:05 UTC, fvacek commented on libshvvisu/src/timeline/graphchannel.h
> +Q_DECLARE_METATYPE(shv::visu::timeline::GraphChannel::Style)
proc?

2021-09-16 09:27 UTC, fvacek requested changes

2021-09-16 09:27 UTC, fvacek commented on libshvvisu/src/timeline/graph.cpp
> +	for (int i = 0; i < channels.count(); ++i) {
create key `channels`

2021-09-16 10:26 UTC, MartinKT commented on libshvvisu/src/timeline/graph.cpp
> +	for (int i = 0; i < channels.count(); ++i) {
doplneno

2021-09-16 12:38 UTC, merged