Add support for LDAP
silicon-heaven/libshv pull request #271
Opened 2023-03-31 14:41 UTC by syyyr

2023-03-31 14:53 UTC, fvacek requested changes

2023-03-31 14:53 UTC, fvacek commented on libshvbroker/src/brokerapp.cpp
> +class AuthThread : public QThread {
`LdapAuthThread`

2023-03-31 14:53 UTC, fvacek commented on libshvbroker/src/brokerapp.cpp
> +	Q_SIGNAL void resultReady(const chainpack::UserLoginResult& s);
I still feel, that `Q_SIGNAL void resultReady(const chainpack::UserLoginResult& s, QStringList user_groups);` or extending `UserLoginResult` by field `userLoginGroups` will be better design. I do not like to use 2 signals for one event.

2023-03-31 14:57 UTC, fvacek commented on libshvbroker/src/brokerapp.cpp
> +		if (auto result = BrokerApp::instance()->aclManager()->checkPassword(m_ctx); result.passwordOk) {
still access to foreing thread object

2023-03-31 15:18 UTC, syyyr commented on libshvbroker/src/brokerapp.cpp
> +		if (auto result = BrokerApp::instance()->aclManager()->checkPassword(m_ctx); result.passwordOk) {
fixed by not doing this in the thread

2023-03-31 15:19 UTC, syyyr commented on libshvbroker/src/brokerapp.cpp
> +class AuthThread : public QThread {
done

2023-04-01 13:47 UTC, fvacek approved these changes

2023-04-01 13:47 UTC, merged