Shv3 MetaMethods
silicon-heaven/libshv pull request #435
Opened 2024-03-13 15:38 UTC by syyyr

2024-03-13 21:10 UTC, fvacek requested changes

2024-03-13 21:10 UTC, fvacek commented on libshvchainpack/src/chainpack/metamethod.cpp
> +	Param = 3,
ParamType

2024-03-13 21:10 UTC, fvacek commented on libshvchainpack/src/chainpack/metamethod.cpp
> +	Result = 4,
ResultType

2024-03-13 21:10 UTC, fvacek commented on libshvchainpack/include/shv/chainpack/metamethod.h
> +		RpcValue result;
```suggestion
		std::string paramType;
```

2024-03-13 21:10 UTC, fvacek commented on libshviotqt/src/node/filenode.cpp
> +	{M_SIZE, cp::MetaMethod::Flag::LargeResultHint, "void", "ret", cp::MetaMethod::AccessLevel::Browse},
```suggestion
	{M_SIZE, cp::MetaMethod::Flag::LargeResultHint, "UInt", "void", cp::MetaMethod::AccessLevel::Browse},
```

2024-03-13 21:10 UTC, fvacek commented on libshviotqt/src/node/filenode.cpp
> +	{M_READ, cp::MetaMethod::Flag::LargeResultHint, "void", "ret", cp::MetaMethod::AccessLevel::Read, {}
```suggestion
	{M_READ, cp::MetaMethod::Flag::LargeResultHint, "void", "Blob", cp::MetaMethod::AccessLevel::Read, {}
```

2024-03-13 21:10 UTC, fvacek commented on libshvchainpack/include/shv/chainpack/metamethod.h
> +	AccessLevel m_accessGrant;
```suggestion
	AccessLevel m_accessLevel;
```

2024-03-13 21:10 UTC, fvacek commented on libshvchainpack/include/shv/chainpack/metamethod.h
> +	RpcValue accessGrant() const;
```suggestion
	AccessLevel accessLevel() const;
```

2024-03-14 10:28 UTC, syyyr commented on libshvchainpack/include/shv/chainpack/metamethod.h
> +	AccessLevel m_accessGrant;
done

2024-03-14 10:29 UTC, syyyr commented on libshvchainpack/src/chainpack/metamethod.cpp
> +	Result = 4,
done

2024-03-14 10:29 UTC, syyyr commented on libshvchainpack/src/chainpack/metamethod.cpp
> +	Param = 3,
done

2024-03-14 10:29 UTC, syyyr commented on libshvchainpack/include/shv/chainpack/metamethod.h
> +		Signal(std::string name, std::string result);
done

2024-03-19 09:25 UTC, syyyr commented on libshvchainpack/include/shv/chainpack/accessgrant.h
done

2024-03-19 10:15 UTC, syyyr commented on libshviotqt/src/node/filenode.cpp
> +	{M_SIZE, cp::MetaMethod::Flag::LargeResultHint, "void", "ret", cp::MetaMethod::AccessLevel::Browse},
done

2024-03-19 10:15 UTC, syyyr commented on libshviotqt/src/node/filenode.cpp
> +	{M_READ, cp::MetaMethod::Flag::LargeResultHint, "void", "ret", cp::MetaMethod::AccessLevel::Read, {}
Done

2024-03-19 10:15 UTC, syyyr commented on libshvchainpack/include/shv/chainpack/metamethod.h
> +	RpcValue accessGrant() const;
Done

2024-03-19 10:21 UTC, syyyr commented on examples/cli/minimalshvbroker/src/application.cpp
> +			{shv::chainpack::Rpc::METH_DIR, shv::chainpack::MetaMethod::Flag::None, "param", "ret", shv::chainpack::MetaMethod::AccessLevel::Browse},
done

2024-03-20 13:37 UTC, merged